name: Deploy Next.js to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ hashFiles('package-lock.json') && 'npm' || hashFiles('yarn.lock') && 'yarn' || 'pnpm' }}

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci;
          else npm install;
          fi

      - name: Build with Next.js
        run: npx next build

      - name: Fix Jekyll Underscore Issue
        run: touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4